<div style="margin-top: 50px; background-color: gray;" class="container">
    <div class="row">
        <h1 style="text-align: center; color: red; font-size: 70px;"> TEAM SECRET </h1>
        <h2 style="text-align: center; color: black;font-size: 35px;"> Integrantes </h2>
        <div class="row">
            <h3 style="text-align: center; color: aqua;font-size: 25px;"> Alfonso Pinto Iglesias </h3>
            <h3 style="text-align: center; color: aqua;font-size: 25px;"> Jordy Huaman Luis</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-10">
            <p class="secret">
                <img style="padding-left: 600px;" src="<?= URL . 'images/secret.png' ?>" alt="logo" class="img-fluid">
            </p>
        </div>
    </div>
</div>

<!-- Footer -->
<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <ul class="list-unstyled">
                    <li>
                        <h5 style="text-align: center;" class="font-weight-bold"><i class="far fa-copyright"></i> TEAM SECRET 2021</h5>
                    </li>
                    <li style="text-align: center;"> Todos los derechos reservados </li>
                </ul>
            </div>
        </div>
    </div>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"></script>