<?php $this->layout('../layouts/layout', ['title' => 'SecretShop|CATEGORIA']) ?>

<?php $this->push('styles'); ?>
<!-- //link de css  -->
<?php $this->end(); ?>
<?php $this->push('contents'); ?>

<div class="container">
    <h1>Bienvenidos</h1>
    <div class="row">
        <div class="col-sm-4">
            <a href="#" class="btn btn-primary btn-block">Nuevo</a>
        </div>
    </div>
    <br>
</div>

<?php $this->end(); ?>
<?php $this->push('scripts'); ?>
<!-- //link js  -->
<?php $this->end(); ?>