<?php $this->layout('../layouts/layout', ['title' => 'SecretShop|CATEGORIA']) ?>

<?php $this->push('styles'); ?>
<!-- //link de css  -->
<?php $this->end(); ?>
<?php $this->push('contents'); ?>

<div class="container">
    <?php echo env('DB_DATABASE') ?>
    <h1> SecretShop - CATEGORIA </h1>
    <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum nihil iste quaerat, qui expedita minima maxime dolore corrupti rem? Fuga ab earum eius illum atque rerum tenetur quidem fugit tempore.
    </p>
    <?php myEcho($data) ?>

</div>
<?php $this->end(); ?>
<?php $this->push('scripts'); ?>
<!-- //link js  -->
<?php $this->end(); ?>