<div class="container">
    <div class="row">
        <div class="col-sm-12">

            <h1>Usuarios tipo - Detalle</h1>

            <form id="myForm" action="<?= URL . 'usuarios_tipo/save' ?>" method="post">


                <input type="text" name="idtipo" value="<?= $data->IdTipo ?>">

                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label for="idnombre">nombre</label>
                            <input type="text" name="nombre" id="id_nombre" class="form-control" value="<?= $data->Nombre ?>">

                        </div>
                    </div>
                </div>
                <div class="row">

                    <div class="col-sm-4">
                        <div class="form-group">
                            <input type="checkbox" name="estado" id="idestado" class="form-check-input" <?= ($data->Estado == 1) ? "checked" : "" ?> <label class="form-check-label" for="idestado">Estado</label>


                        </div>

                    </div>
                    <div class="col-sm-8">

                    </div>

                </div>
                <br>
                <div class="row">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block">Guardar</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <br>
</div>
