<?php $this->layout('../layouts/layout', ['title' => 'SECRETSHOP']) ?>

<?php $this->push('styles'); ?>
<!-- //link de css  -->
<?php $this->end(); ?>
<?php $this->push('contents'); ?>

<div class="container">
    <br>

    <h1> SECRETSHOP - Bienvenidos </h1>
    <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum nihil iste quaerat, qui expedita minima maxime dolore corrupti rem? Fuga ab earum eius illum atque rerum tenetur quidem fugit tempore.
    </p>

</div>
<?php $this->end(); ?>
<?php $this->push('scripts'); ?>
<!-- //link js  -->
<?php $this->end(); ?>