<div class="container-fluid container-web-page">
    <h3 class="text-center text-uppercase poppins-regular font-weight-bold">Nuestros platillos más populares</h3>
    <div class="container-cards full-box">

        <div class="card shadow-1-strong">
            <img class="card-img-top" src="./assets/platillos/platillo.jpg" alt="nombre_platillo">
            <div class="card-body text-center">
                <h5 class="card-title font-weight-bold">Nombre o titulo del platillo</h5>
                <p class="card-text lead"><span class="badge bg-secondary">$25.00 USD</span></p>
            </div>
            <div class="card-body text-center">
                <button type="button" class="btn btn-success btn-sm"><i class="fas fa-shopping-bag fa-fw"></i> &nbsp; Agregar</button>
                &nbsp; &nbsp;
                <a href="details.html" class="btn btn-info btn-sm"><i class="fas fa-utensils fa-fw"></i> &nbsp; Detalles</a>
            </div>
        </div>

        <div class="card shadow-1-strong">
            <img class="card-img-top" src="./assets/img/img_not_found.jpg" alt="nombre_platillo">
            <div class="card-body text-center">
                <h5 class="card-title font-weight-bold">Nombre o titulo del platillo</h5>
                <p class="card-text lead"><span class="badge bg-secondary">$25.00 USD</span></p>
            </div>
            <div class="card-body text-center">
                <button type="button" class="btn btn-success btn-sm"><i class="fas fa-shopping-bag fa-fw"></i> &nbsp; Agregar</button>
                &nbsp; &nbsp;
                <a href="details.html" class="btn btn-info btn-sm"><i class="fas fa-utensils fa-fw"></i> &nbsp; Detalles</a>
            </div>
        </div>

        <div class="card shadow-1-strong">
            <img class="card-img-top" src="./assets/platillos/platillo.jpg" alt="nombre_platillo">
            <div class="card-body text-center">
                <h5 class="card-title font-weight-bold">Nombre o titulo del platillo</h5>
                <p class="card-text lead"><span class="badge bg-secondary">$25.00 USD</span></p>
            </div>
            <div class="card-body text-center">
                <button type="button" class="btn btn-success btn-sm"><i class="fas fa-shopping-bag fa-fw"></i> &nbsp; Agregar</button>
                &nbsp; &nbsp;
                <a href="details.html" class="btn btn-info btn-sm"><i class="fas fa-utensils fa-fw"></i> &nbsp; Detalles</a>
            </div>
        </div>

    </div>
    <br>
    <p class="text-center"><a href="menu.html" class="btn btn-primary"><i class="fas fa-hamburger fa-fw"></i> &nbsp; Ir al menu</a></p>
</div>

<hr>