    <div class="container container-web-page">
        <h3 class="text-center text-uppercase poppins-regular font-weight-bold">Nuestros servicios</h3>
        <br>
        <div class="row">
            <div class="col-12 col-sm-6 col-md-4">
                <p class="text-center"><i class="fas fa-shipping-fast fa-5x"></i></p>
                <h5 class="text-center text-uppercase poppins-regular font-weight-bold">Envíos a domicilio</h5>
                <p class="text-center">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad possimus modi repellendus? Expedita, vitae rerum at aliquam eligendi soluta veniam ut dolor facere fugiat quod, maxime ad accusamus quisquam.</p>
            </div>
            <div class="col-12 col-sm-6 col-md-4">
                <p class="text-center"><i class="fas fa-utensils fa-5x"></i></p>
                <h5 class="text-center text-uppercase poppins-regular font-weight-bold">Ventas al por mayor</h5>
                <p class="text-center">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad possimus modi repellendus? Expedita, vitae rerum at aliquam eligendi soluta veniam ut dolor facere fugiat quod, maxime ad accusamus quisquam.</p>
            </div>
            <div class="col-12 col-sm-6 col-md-4">
                <p class="text-center"><i class="fas fa-store-alt fa-5x"></i></p>
                <h5 class="text-center text-uppercase poppins-regular font-weight-bold">Reservaciones de local</h5>
                <p class="text-center">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione ad possimus modi repellendus? Expedita, vitae rerum at aliquam eligendi soluta veniam ut dolor facere fugiat quod, maxime ad accusamus quisquam.</p>
            </div>
        </div>
    </div>

    <hr>