<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title>Restaurant</title>

    <!-- Normalize V8.0.1 -->
    <link rel="stylesheet" href="./css/normalize.css">

    <!-- MDBootstrap V5 -->
    <link rel="stylesheet" href="./css/mdb.min.css">

    <!-- Font Awesome V5.15.1 -->
    <link rel="stylesheet" href="./css/all.css">

    <!-- Sweet Alert V10.13.0 -->
    <script src="./js/sweetalert2.js"></script>

    <!-- General Styles -->
    <link rel="stylesheet" href="./css/style.css">

</head>

<body>

    <?php require_once MAINPATH . 'app/views/layouts/partials/_header.phtml' ?>

    <main role="main">
        <?= $this->section('contents') ?>
    </main>

    <?php require_once MAINPATH . 'app/views/layouts/partials/_banner.phtml' ?>

    <?php require_once MAINPATH . 'app/views/layouts/partials/_container1.phtml' ?>

    <?php require_once MAINPATH . 'app/views/layouts/partials/_container-fluid.phtml' ?>

    <?php require_once MAINPATH . 'app/views/layouts/partials/_container2.phtml' ?>

    <?php require_once MAINPATH . 'app/views/layouts/partials/_header.phtml' ?>


    <!-- MDBootstrap V5 -->
    <script src="./js/mdb.min.js"></script>

    <!-- General scripts -->
    <script src="./js/main.js"></script>
</body>

</html>