<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title><?= $this->e($title) ?> </title>
    <title>Restaurant</title>

    <!-- Normalize V8.0.1 -->
    <link rel="stylesheet" href="<?= URL . 'css/normalize.css' ?>">

    <!-- MDBootstrap V5 -->
    <link rel="stylesheet" href="<?= URL . 'css/mdb.min.css' ?>">

    <!-- Font Awesome V5.15.1 -->
    <link rel="stylesheet" href="<?= URL . 'css/all.css' ?>">

    <!-- Sweet Alert V10.13.0 -->
    <!-- <script src="<?= URL . './js/sweetalert2.js' ?>"></script> -->

    <!-- General Styles -->
    <link rel="stylesheet" href="<?= URL . './css/style.css' ?>">


    <?= $this->section('styles') ?>
</head>

<body>
    <div class="body-wrapper">
        <?php require_once MAINPATH . 'app/views/layouts/partials/_header.phtml' ?>
        <main role="main">
            <?= $this->section('contents') ?>
        </main>
        <?php require_once MAINPATH . 'app/views/layouts/partials/_banner.phtml' ?>
        <?php require_once MAINPATH . 'app/views/layouts/partials/_container1.phtml' ?>
        <?php require_once MAINPATH . 'app/views/layouts/partials/_container-fluid.phtml' ?>
        <?php require_once MAINPATH . 'app/views/layouts/partials/_container2.phtml' ?>
        <?php require_once MAINPATH . 'app/views/layouts/partials/_footer.phtml' ?>
    </div>
    <?= $this->section('myModal') ?>

    <script src="<?= URL . 'js/jquery-3.6.0.min.js' ?>"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"></script>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="<?= URL . 'js/main.js' ?>"></script>

    <?= $this->section('scripts') ?>
</body>

</html> 