<?php $this->layout('../layouts/layout', ['title' => 'SecretShop|COMPROBANTE']) ?>

<?php $this->push('styles'); ?>
<!-- //link de css  -->
<?php $this->end(); ?>
<?php $this->push('contents'); ?>

<div class="container">
    <h1>Comprobante</h1>
    <div class="row">
        <div class="col-sm-4">
            <a is-modal="true" href="<?= URL . "/comprobante/detail/" ?>" class="btn btn-primary btn-block">Nuevo</a>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th style="width:10%">ID</th>
                        <th style="width:30%">Nombre</th>
                        <th style="width: 10%;">Estado</th>
                        <th style="width:10%"></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($data as $row) : ?>
                        <tr>
                            <td><?= $row->IdComprobante ?></td>
                            <td><?= $row->Nombre ?></td>
                            <td><?= $row->Estado ?></td>
                            <td>
                                <a is-modal="true" href="<?= URL . "comprobante/detail/{$row->IdComprobante}" ?>" title="Editar" class="btn btn-sm btn-primary"> <i class="fa fa-pen"></i></a>

                                <a href="<?= URL . "comprobante/delete/{$row->IdComprobante}" ?>" title="Eliminar" class="btn btn-sm btn-danger" onclick="return confirm('¿Está seguro de eliminar este registro?')"><i class="fa fa-trash"></i></a>

                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
    <br>
</div>


<?php $this->stop(); ?>
<?php $this->start('myModal') ?>
<?php
$title = 'Comprobante - Insertar ';
$size = GRANDE;
include MAINPATH . 'app/views/layouts/partials/_modalGenerico.phtml';
?>
<?php $this->stop() ?>

<?php $this->push('scripts') ?>
<script src="<?= URL . 'js/scripts/modal_crud.js' ?>"></script>

<?php $this->end() ?>>